/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface LoginRequest {
  email: string;
  password: string;
}

export interface RegisterRequest {
  email: string;
  fullName: string;
  password: string;
}
