/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface InsertProductData {
  price: number;
  productDescription?: string | null | '';
  productName: string;
  stockQuantity: number;
}

export interface UpdateProductData {
  price?: number;
  productDescription?: string | null | '';
  productName?: string;
  stockQuantity?: number;
}

export interface productListFilter {
  limit?: number;
  offset?: number;
  productName?: string;
}
