/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface UpdateUserRequest {
  email?: string;
  fullName?: string;
  password?: string;
}
